version: '3'

networks: 
    net:
    database:
volumes: 
    dados:
services:
    db:
        image: postgres:9.6
        environment: 
            POSTGRES_USER: 'evolux'
            POSTGRES_PASSWORD: 'evolux'
            POSTGRES_DB: 'evolux'
        volumes: 
            - dados:/var/lib/postgresql/data
        networks: 
            - database
    app:
        build: ./App
        command: gunicorn --bind 0.0.0.0:5000 app:app
        volumes: 
            - ./App:/usr/src/app
        expose:  
            - 5000
        networks:
            - net
            - database
        
        depends_on: 
            - db
    web:
        build: ./web
        ports: 
            - 80:80
        depends_on: 
            - app
        networks: 
            - net

    
